var annotated_dup =
[
    [ "KUKA", "namespace_k_u_k_a.html", [
      [ "FRI", "namespace_k_u_k_a_1_1_f_r_i.html", [
        [ "ClientApplication", "class_k_u_k_a_1_1_f_r_i_1_1_client_application.html", "class_k_u_k_a_1_1_f_r_i_1_1_client_application" ],
        [ "IClient", "class_k_u_k_a_1_1_f_r_i_1_1_i_client.html", "class_k_u_k_a_1_1_f_r_i_1_1_i_client" ],
        [ "IConnection", "class_k_u_k_a_1_1_f_r_i_1_1_i_connection.html", "class_k_u_k_a_1_1_f_r_i_1_1_i_connection" ],
        [ "FRIException", "class_k_u_k_a_1_1_f_r_i_1_1_f_r_i_exception.html", "class_k_u_k_a_1_1_f_r_i_1_1_f_r_i_exception" ],
        [ "LBRClient", "class_k_u_k_a_1_1_f_r_i_1_1_l_b_r_client.html", "class_k_u_k_a_1_1_f_r_i_1_1_l_b_r_client" ],
        [ "LBRCommand", "class_k_u_k_a_1_1_f_r_i_1_1_l_b_r_command.html", "class_k_u_k_a_1_1_f_r_i_1_1_l_b_r_command" ],
        [ "LBRState", "class_k_u_k_a_1_1_f_r_i_1_1_l_b_r_state.html", "class_k_u_k_a_1_1_f_r_i_1_1_l_b_r_state" ],
        [ "TransformationClient", "class_k_u_k_a_1_1_f_r_i_1_1_transformation_client.html", "class_k_u_k_a_1_1_f_r_i_1_1_transformation_client" ],
        [ "UdpConnection", "class_k_u_k_a_1_1_f_r_i_1_1_udp_connection.html", "class_k_u_k_a_1_1_f_r_i_1_1_udp_connection" ],
        [ "ClientData", "struct_k_u_k_a_1_1_f_r_i_1_1_client_data.html", "struct_k_u_k_a_1_1_f_r_i_1_1_client_data" ],
        [ "CommandMessageEncoder", "class_k_u_k_a_1_1_f_r_i_1_1_command_message_encoder.html", "class_k_u_k_a_1_1_f_r_i_1_1_command_message_encoder" ],
        [ "MonitoringMessageDecoder", "class_k_u_k_a_1_1_f_r_i_1_1_monitoring_message_decoder.html", "class_k_u_k_a_1_1_f_r_i_1_1_monitoring_message_decoder" ]
      ] ]
    ] ],
    [ "_CartesianVector", "struct___cartesian_vector.html", "struct___cartesian_vector" ],
    [ "_Checksum", "struct___checksum.html", "struct___checksum" ],
    [ "_ConnectionInfo", "struct___connection_info.html", "struct___connection_info" ],
    [ "_FRICommandMessage", "struct___f_r_i_command_message.html", "struct___f_r_i_command_message" ],
    [ "_FriIOValue", "struct___fri_i_o_value.html", "struct___fri_i_o_value" ],
    [ "_FRIMonitoringMessage", "struct___f_r_i_monitoring_message.html", "struct___f_r_i_monitoring_message" ],
    [ "_JointValues", "struct___joint_values.html", "struct___joint_values" ],
    [ "_MessageCommandData", "struct___message_command_data.html", "struct___message_command_data" ],
    [ "_MessageEndOf", "struct___message_end_of.html", "struct___message_end_of" ],
    [ "_MessageHeader", "struct___message_header.html", "struct___message_header" ],
    [ "_MessageIpoData", "struct___message_ipo_data.html", "struct___message_ipo_data" ],
    [ "_MessageMonitorData", "struct___message_monitor_data.html", "struct___message_monitor_data" ],
    [ "_pb_bytes_array_t", "struct__pb__bytes__array__t.html", "struct__pb__bytes__array__t" ],
    [ "_pb_callback_t", "struct__pb__callback__t.html", "struct__pb__callback__t" ],
    [ "_pb_extension_t", "struct__pb__extension__t.html", "struct__pb__extension__t" ],
    [ "_pb_extension_type_t", "struct__pb__extension__type__t.html", "struct__pb__extension__type__t" ],
    [ "_pb_field_t", "struct__pb__field__t.html", "struct__pb__field__t" ],
    [ "_pb_istream_t", "struct__pb__istream__t.html", "struct__pb__istream__t" ],
    [ "_pb_ostream_t", "struct__pb__ostream__t.html", "struct__pb__ostream__t" ],
    [ "_RobotInfo", "struct___robot_info.html", "struct___robot_info" ],
    [ "_TimeStamp", "struct___time_stamp.html", "struct___time_stamp" ],
    [ "_Transformation", "struct___transformation.html", "struct___transformation" ],
    [ "IOAccessClient", "class_i_o_access_client.html", "class_i_o_access_client" ],
    [ "LBRJointSineOverlayClient", "class_l_b_r_joint_sine_overlay_client.html", "class_l_b_r_joint_sine_overlay_client" ],
    [ "LBRTorqueSineOverlayClient", "class_l_b_r_torque_sine_overlay_client.html", "class_l_b_r_torque_sine_overlay_client" ],
    [ "LBRWrenchSineOverlayClient", "class_l_b_r_wrench_sine_overlay_client.html", "class_l_b_r_wrench_sine_overlay_client" ],
    [ "MyLBRClient", "class_my_l_b_r_client.html", "class_my_l_b_r_client" ],
    [ "pb_field_iterator_t", "structpb__field__iterator__t.html", "structpb__field__iterator__t" ],
    [ "repeatedDoubleArguments", "structrepeated_double_arguments.html", "structrepeated_double_arguments" ],
    [ "repeatedIntArguments", "structrepeated_int_arguments.html", "structrepeated_int_arguments" ],
    [ "SimulatedTransformationProviderClient", "class_simulated_transformation_provider_client.html", "class_simulated_transformation_provider_client" ],
    [ "TransformationProviderClient", "class_transformation_provider_client.html", "class_transformation_provider_client" ]
];