FROM mmatosin/rl_app
LABEL authors="mirko"
# Install Python3 and Doxygen
# Install Python3 and Doxygen
RUN apt-get update && \
    apt-get install -y python3-dev python3 python3-pip doxygen graphviz \
    libssl-dev libffi-dev

# Install matplotlib
RUN python3 -m pip install matplotlib


ENV PATH="${PATH}:/usr/bin/"

    # Set the working directory back to /app for the final build
WORKDIR /app
COPY . .
RUN ls -l
# Build your project
RUN mkdir build && \
    cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_MAKE_PROGRAM=ninja -DBUILD_FRI_APPS:BOOL=OFF -G \
    Ninja -S . -B build && \
    cmake --build build --parallel 12

