services:
  base:
    build:
      dockerfile: ./DockerfileBaseImage
      context: ..
    container_name: localhost/mybase

  rlapp:
    build:
      dockerfile: ./Dockerfile_rl
      context: ..
    container_name: localhost/rl-app
    depends_on:
      - base
  # We dont need the others container running. This compose file is only a sample and easy way to build all deps
  masters:
    build:
      dockerfile: ./Dockerfile_mastersApp
      context: ..
    container_name: localhost/masters-app
    depends_on:
      - base
      - rlapp
