ARG BASE_IMAGE=localhost/rl-app
FROM $BASE_IMAGE AS roblib

LABEL org.zimmer.image.authors="mirko"
LABEL image_name="localhost/masters-app"
LABEL org.image.authors="@mightymirko"
LABEL "com.example.vendor"="AndAction"
LABEL version="1.0"
LABEL description="Mount and dev"
ENV DEBIAN_FRONTEND noninteractive


WORKDIR /app

ENV USER $USERNAME
USER $USER

CMD /bin/bash
